### ISSUE TITLE
Issues with load_starsim in R

### ISSUE THREAD

**Issue by ntparker3** [starsimhub/rstarsim#13]
Hi there,

I'm trying to work with starsim in R and have had issues with the load_starsim function. I have starsim running and working in Python so it's not a huge deal to get it to work in R, but I am much more comfortable with R, so it would be great if it was possible to use it in R as well. I have tried all the below methods for loading in starsim:

library(starsim)
load_starsim('base')

load_starsim("starsim_env")

load_starsim('miniconda')

load_starsim('r-starsim')

but each returns me a error saying: 
Error in py_module_import(module, convert = convert) : 
  OSError: Could not find/load shared object file
Run `reticulate::py_last_error()` for details.

I'm able to run starsim in my base conda environment with Python, so I'm pretty confident that "base" should be working and is the correct environment to call. Is it possible that there is something wrong with my reticulate package? I've never used reticulate before so I'm unsure about its use. Thank you for you help!

-Noah Parker

**Comment by cliffckerr** [comment]
Sorry for the issue, @ntparker3! Best approach is probably to test different pieces and see where the error is arising. You can try the `reticulate::py_last_error()` command it suggests, it might be helpful (or it might not!).

It might be something to do with how `reticulate` is handling the Python environments, especially if you have multiple different Python versions on your machine.

First, find the path to the Python executable that has Starsim installed:
```
$ python # should load base environment
```
```py
import starsim # check that starsim import works
import sys; print(sys.executable) # find the path to the python interpreter
```
Depending on your system, since it's the base environment, it should be something like `/Users/ntparker3/anaconda3/bin/python`.

Next, see what environment Reticulate uses by default:
```
$ R
```
```R
library(reticulate)
py_config()
```

My guess is that it will _not_ be the same environment as you had above.

In that case, you can manually direct `reticulate` to the right environment:
```R
library(reticulate)
use_python("/Users/ntparker3/anaconda3/bin/python")
```

Now the import should work:
```R
ss <- import("starsim")
```

If that still doesn't work, in that same environment, try each of the dependencies individually:
```R
np <- import("numpy")
pd <- import("pandas")
plt <- import("matplotlib.pyplot")
sc <- import("sciris")
nb <- import("numba")
nx <- import("networkx")
op <- import("optuna")
```

If one or more of the imports fails, you might need to reinstall it (or, at this point, probably easiest to set up a fresh virtual environment). If all the imports succeed but Starsim still doesn't, then I will be very confused, but let's cross that bridge if we come to it :)

**Comment by ntparker3** [comment]
Thank you for the quick response! Had to reinstall it and manually direct reticulate, but was able to get it to work. Thanks for your help.

**Comment by ntparker3** [comment]
While I have you though, one further question: I'm playing around with the contact networks and I was wondering if it was possible to upload your own contact network. I've created my own dynamic contact network that has person1, person2, and the time step that they were in contact for. I was able to upload a dataframe into Python and use the ss.Network function to create the table containing p1, p2, beta, and dur. However, it's not clear to me how to provide the step descriptor. Is this something that can be provided in that table (i.e. a step variable/column) or through a function? Or do I need to create the network through starsim itself?

**Comment by cliffckerr** [comment]
You would need a custom class for that. Here's an example (sorry it's in Python!):
```py
"""
Example of a custom contact network
"""
import numpy as np
import starsim as ss

# Set model parameters
n = 1000
dur = 100
start = 2000

# Create custom contact network with increasing contact probability over time
n_contacts = np.linspace(start=1, stop=20, num=dur+1) # increase the number of contacts over time
contact_dict = {}
agents = np.arange(n)
for i in range(dur+1): # loop over each timestep
    total_contacts = int(n*n_contacts[i]) # total number of contacts in whole population
    p1 = np.random.choice(agents, total_contacts) # one person in pair
    p2 = np.random.choice(agents, total_contacts) # other person in pair
    contact_dict[i] = dict(p1=p1, p2=p2) # the contacts for this timestep

# Create our custom network
class CustomNet(ss.Network):
    def __init__(self, contact_dict):
        super().__init__()
        self.contact_dict = contact_dict

    def step(self):
        contacts = self.contact_dict[self.ti] # pull out contacts for this timestep
        self.edges.p1 = contacts['p1'] # reset the contacts (edges)
        self.edges.p2 = contacts['p2']
        self.edges.beta = np.ones(len(self)) # relative transmission probability
        self.validate() # ensure everything has the correct type

# Create our simulations
pars = dict( # shared parameters
    n_agents = n,
    dur = dur,
    start = start,
    diseases = 'sis',
)

random_sim = ss.Sim(
    pars = pars,
    label = 'RandomNet',
    networks = 'random',
)

custom_sim = ss.Sim(
    pars = pars,
    label = 'CustomNet',
    networks = CustomNet(contact_dict),
)

# Run and plot
random_sim.run()
custom_sim.run()
msim = ss.MultiSim([random_sim, custom_sim])
msim.plot() # nb: you may need to call plt.show() for the plot to appear

# Show the number of edges on each timestep
print(custom_sim.networks.customnet.results.n_edges)
```
![image](https://github.com/user-attachments/assets/00f3ee4b-bfcf-437a-866a-c347cc22290b)

You can see the effect of increasing contacts: the epidemic takes longer to take off for `CustomNet` than `Randomnet`, but then it stabilizes at a higher number of infections.

**Comment by ntparker3** [comment]
Awesome, thank you for your help. I couldn't find the "ti" function which was the missing link, but now able to upload my own custom networks. Excited to play around with these models!

**Comment by cliffckerr** [comment]
Thank you, let us know if we can help with anything else! Going to close this issue.
